[package]
name = "params"
version = "0.1.0"
authors = ["Jon Lamb"]
edition = "2018"

[dependencies]
static_assertions = "1.1.0"
bitfield = "0.13.2"

[dependencies.byteorder]
version = "1.3.2"
default-features = false
