# paramdb.toml
#
# UDP bcast port 9876
# TCP port 9877

[[node]]
id = 1
name = "template_node1"
desc = "Template Box Controller Node"
ip = "192.168.1.39"

[[node]]
id = 2
name = "template_node2"
desc = "Template Box Controller Node"
ip = "192.168.1.2"
# Won't be monitored in grafana/etc
ignore = true
# zone?

[[parameter]]
id = 100
name = "uptime"
desc = "System uptime, seconds"
ro = true
bcast = true
value_type = "u32"
value = "0"

[[parameter]]
id = 200
name = "eth_link_down_count"
desc = "Ethernet link-down counter"
ro = true
bcast = true
value_type = "u32"
value = "0"

[[parameter]]
id = 300
name = "led_state"
desc = "Red LED state"
value_type = "bool"
value = "true"
