# paramdb.toml
#
# UDP bcast port 9876
# TCP port 9877

# flags:
# ro : externally read-only
# bcast : 
# const : internally and externally read-only
# bcast_on_change

[[node]]
id = 1
name = "template_node1"
desc = "Template Box Controller Node"
ip = "192.168.1.39"

[[node]]
id = 2
name = "template_node2"
desc = "Template Box Controller Node"
ip = "192.168.1.2"
# Won't be monitored in grafana/etc
ignore = true
# zone?

[[parameter]]
id = 100
name = "bcast_interval"
desc = "Broadcast interval, seconds"
value_type = "u32"
value = "5"

[[parameter]]
id = 101
name = "uptime"
desc = "System uptime, seconds"
ro = true
bcast = true
value_type = "u32"
value = "0"

[[parameter]]
id = 200
name = "eth_link_down_count"
desc = "Ethernet link-down counter"
ro = true
bcast = false
value_type = "u32"
value = "0"

[[parameter]]
id = 201
name = "temperature"
desc = "Some temp degrees F"
#ro = true
bcast = true
value_type = "f32"
value = "0.0"

[[parameter]]
id = 300
name = "led_state"
desc = "Red LED state"
value_type = "bool"
value = "true"
bcast = true
bcast_on_change = true
